### ISSUE TITLE
Questions - retrieving the values of CO2 uptake and CH4 release by plants, and diffusion of CO2 and CH4 between atmosphere and water surface.

### ISSUE THREAD

**Issue by yojiyojiyoji** [USEPA/WetQual-GUI#1]
We are currently thinking of using this model, mainly for carbon cycle modelling.
According to Sharifi (2013), CO2 uptake and CH4 release by plant, and diffusion of CO2 and CH4 between atmosphere and water surface are also illustrated but could not see these values in the outputs.
So, I am wondering if these values are retrievable from the model. (We will modify the codes if necessary.)
As long as I quickly looked at the codes, it seems to be possible, but I would appreciate it if I could make sure about it.
Thank you in advance for taking your time.

**Comment by yojiyojiyoji** [comment]
We decided to suspending our project for the time being. So, I will close this issue.
Thanks.

**Comment by sisik1967** [comment]
I am sorry that I have just seen the issue. If you decide to continue working on WetQual, please contact Dr. Kalin (https://latifkalin.weebly.com/; E-mail: latif@auburn.edu). Thanks.

**Comment by yojiyojiyoji** [comment]
Thanks for the message.
So, if necessary, we will directly contact him.
Regards
